[package]
name = "messaging"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "messaging"
path = "src/lib.rs"

[dependencies]
kafka = "0.10.0"
model = { path = "../model" }
serde_json = "1.0.118"
